# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMapMatMult <- function(A, B) {
    .Call(`_dvRutils_eigenMapMatMult`, A, B)
}

eigenMapMatInv <- function(A) {
    .Call(`_dvRutils_eigenMapMatInv`, A)
}

eigenMapMatEig <- function(A) {
    .Call(`_dvRutils_eigenMapMatEig`, A)
}

